[run]
init_cmds = [
  ["go", "build", "-o", "./build/github-release-tool"],
	["./build/github-release-tool", "v"]
]
# Watch all directories
watch_all = true
watch_exts = [".go", ".ini", ".toml"]

# Directories to exclude from watching
ignore = [".git", ".travis",".vscode", "vendor", "build", "dist"] 

# Minimum delay between two builds
build_delay = 5

cmds = [
  ["go", "build", "-o", "./build/github-release-tool"],
  ["./build/github-release-tool", "v"]
]
